### ISSUE TITLE
[BUG] PlatformTest does not instantiate and I cannot use supertest

### ISSUE THREAD

**Issue by yaritaft** [TypedProject/ts-express-decorators#1676] opened 2021-12-07 00:44 UTC
## Information

- **Version:** 6.95.0
- Packages: 
"@tsed/ajv": "6.95.0",
    "@tsed/common": "6.95.0",
    "@tsed/core": "6.95.0",
    "@tsed/di": "6.95.0",
    "@tsed/exceptions": "6.95.0",
    "@tsed/json-mapper": "6.95.0",
    "@tsed/platform-express": "6.95.0",
    "@tsed/schema": "6.95.0",
    "@tsed/swagger": "6.95.0",
    "@tsed/typeorm": "6.95.0",

A few sentences describing the overall goals of the issue.

Hello! For some reason Platform Test does not work when I do:

```
 beforeAll(async () => {
    await PlatformTest.bootstrap(Server);
  });

```

When I run the tests it says: 
   **PlatformTest.injector is not initialized. Use PlatformTest.create(): Promise before PlatformTest.invoke() or PlatformTest.injector.
    Example:
    before(async () => {
       await PlatformTest.create()
       await PlatformTest.invoke(MyService, [])
    })**

Then I tried doing:
``` 
 beforeAll(async () => {
    await PlatformTest.bootstrap(Server);
    await PlatformTest.create();
  });
```

When I print with JSON.stringify(PlatformTest.callback()) it says undefined.

Things that I checked and tried:

- Checked that import "@tsed/platform-express"; is inside server.ts
- Added create after bootstrap
- Had to use database without TypeORMService because platform test does not instantiate and connections are not available neither
- Did a fresh reinstall by erasing node_modules and package-lock.json
- I have every tsed depedency with same version

device.integration.test.ts

```typescript
import { PlatformTest } from "@tsed/common";
import * as SuperTest from "supertest";
import { Server } from "../../server";
import { Connection, createConnection } from "typeorm";
import { DeviceEntity } from "../../entities/Device.entity";
import { DeviceAccountEntity } from "../../entities/DeviceAccount.entity";
import { PlatformExpress } from "@tsed/platform-express";
import { UserController } from "../../controllers/ReportController";

describe("Rest", () => {
  // bootstrap your Server to load all endpoints before run your test
  let request: SuperTest.SuperTest<SuperTest.Test>;
  let connection: Connection | undefined;
  // beforeAll(PlatformTest.bootstrap(Server));
  // // afterAll(PlatformTest.reset);
  beforeAll(async () => {
    await PlatformTest.bootstrap(Server);
    await PlatformTest.create();
    await PlatformTest.invoke(UserController, []);
  });

  beforeAll(() => {
    console.log(JSON.stringify(PlatformTest.callback()));
    request = SuperTest.agent(PlatformTest.callback());
  });

  beforeEach(async () => {
    await createConnection({
      name: "seed",
      type: "postgres",
      host: "localhost",
      port: 5432,
      username: "postgres",
      password: "123456789",
      database: "mydatabase",
      synchronize: true,
      entities: ["dist/**/*.entity.js"],
    }).then((newConnection) => {
      connection = newConnection;
    });
    await connection.getRepository(DeviceEntity).delete({});
    await connection.getRepository(DeviceAccountEntity).delete({});
  });
  afterAll(async () => {
    await PlatformTest.reset();
    await connection.close();
  });

  describe("Post /api/session/device/register", () => {
    it("Register user", async () => {
      const bodyDeviceRegistry = {
        serialNumber: "1",
        password: "1",
      };
      await connection.query(
        "INSERT INTO device (\"serialNumber\", \"deviceAccountId\", \"mostRecentFirmwareVersion\") VALUES ('1','1','222');"
      );
      await connection.query(
        "INSERT INTO device_account (\"serialNumber\",\"token\", \"hashedPass\", \"salt\",  \"deviceAccountId\") VALUES ('1', '482ffc8e-79cf-40b1-a9e0-586334c250bb','$2a$10$smyIgNKTBbBTG9TT8q.V1OMvCociUHuDghjzeMip0rIPunaa.KL/C','$2a$10$smyIgNKTBbBTG9TT8q.V1O','1')"
      );
      await request.post("/api/session/device/register").send(bodyDeviceRegistry).set("Accept", "application/json").expect(200);
    });
  });
});

```

Server.ts
```typescript
import { Configuration, Inject, PlatformApplication } from "@tsed/common";
import * as cors from "cors";
import * as bodyParser from "body-parser";
import * as compress from "compression";
import * as cookieParser from "cookie-parser";
import "@tsed/platform-express";
import * as methodOverride from "method-override";
import "@tsed/typeorm";
const config = require("dotenv").config({ path: "./.env" });

const rootDir = __dirname;

const whitelist = ["127.0.0.1:80", "0.0.0.0:8080", "localhost:3000", "http://localhost:3000", "https://yaritaft.github.io"];
const corsOptions = {
  credentials: true,
  origin: function (origin, callback) {
    console.log(origin);
    if (whitelist.indexOf(origin) !== -1 || !origin) {
      callback(null, true);
    } else {
      callback(new Error("Domain not allowed by CORS"));
    }
  },
};

@Configuration({
  rootDir,
  debug: process.env.PORT === undefined, // to check if it is dev
  port: process.env.PORT || 8080, // Because heroku automatically sets port.
  httpPort: `0.0.0.0:${process.env.PORT || 8080}`,
  acceptMimes: ["application/json"],
  mount: {
    "/api": [`${rootDir}/controllers/*.{ts,js}`], // using componentScan
  },
  componentsScan: [`${rootDir}/services/**/*.{ts,js}`],
  typeorm: [
    {
      name: "default",
      type: "postgres",
      url: process.env.DATABASE_URL || config.DATABASE_URL,
      ssl: process.env.DATABASE_URL ? true : false, // If env var is not set then it is dev
      entities: [`${rootDir}/**/*.entity.js`, `${rootDir}/**/*.entity.{ts,js}`],
      migrations: [`${rootDir}/migrations/**/*.js`],
      subscribers: [`${rootDir}/subscriber/*.js}`],
    },
    {
      name: "seed",
      migrationsTableName: "seed_migrations",
      migrations: ["src/seeds/*.ts"],
      cli: {
        migrationsDir: "src/seeds",
      },
      type: "postgres",
      host: "localhost",
      port: 5432,
      username: "postgres",
      password: "123456789",
      database: "mydatabase",
      synchronize: false,
      logging: true,
    },
  ],
})
export class Server {
  @Inject()
  app: PlatformApplication;

  @Configuration()
  settings: Configuration;

  /**
   * This method let you configure the express middleware required by your application to works.
   * @returns {Server}
   */
  public $beforeRoutesInit(): void | Promise<any> {
    this.app
      .use(cookieParser())
      .use(compress({}))
      .use(cors(corsOptions))
      .use(methodOverride())
      .use(bodyParser.json())
      .use(
        bodyParser.urlencoded({
          extended: true,
        })
      );
  }
}

```

Thanks in advance!

**Comment by Romakita** [comment] 2021-12-07 03:06
Hello @yaritaft 

I'll try to reproduce. But the PlatformTest.bootstrap() function make a PlatformTest.create() for your so this is not necessary.

>  Added create after bootstrap

Remove it.

> Had to use database without TypeORMService because platform test does not instantiate and connections are not available neither

It's wrong, if you use PlatformTest.boostrapt(Server), the connexion will be iniatiliazed according to the server configuration.
the connection will be created. The is the main difference between `.create()` and `.bootstrap()`.

This integration test confirm my point: https://github.com/tsedio/tsed/blob/production/packages/orm/typeorm/test/integration.spec.ts  ^^

**Comment by Romakita** [comment] 2021-12-07 03:44
https://github.com/tsedio/tsed-example-typeorm/blob/master/src/controllers/pages/IndexCtrl.integration.spec.ts
https://github.com/tsedio/tsed-example-typeorm/blob/master/src/controllers/rest/passport/PassportCtrl.integration.spec.ts

**Comment by Romakita** [comment] 2021-12-07 03:55
Ok I think, I reproduce issue when I run all test in the project example but not when I run only one test file

**Comment by Romakita** [comment] 2021-12-07 03:59
Ok I reproduce the bug when I run all test with jest. Running one test file works ...

**Comment by Romakita** [comment] 2021-12-07 04:08
Finally, I'm not able to reproduce your issue. The project example works as expected. Is it possible to have an acces to your repo or have small reproducible example please :)

**Comment by yaritaft** [comment] 2021-12-07 15:57
Hello Romakita! Thank you very much for that quick answer. Sure:
Here you have my repo and the **BRANCH: reproduce_bug**
https://github.com/yaritaft/smart_air_conditioning/tree/reproduce_bug

You have to run "./up.sh" and then run npm run test:unit
And In that way you should be able to reproduce the issue in this test **admin.integration.test.ts**

  ● Rest › Post /api/session/admin/login › Register user

    PlatformTest.injector is not initialized. Use PlatformTest.create(): Promise before PlatformTest.invoke() or PlatformTest.injector.
    Example:
    before(async () => {
       await PlatformTest.create()
       await PlatformTest.invoke(MyService, [])
    })

**Comment by Romakita** [comment] 2021-12-07 16:05
Thanks @yaritaft I'll checkout the project and investigate ;)

**Comment by yaritaft** [comment] 2021-12-07 16:08
Thank you @Romakita . One more thing, I tested with tsed version 6.11.3 and with version 6.95.1 and with both I get the same issue. Maybe that can help a little bit.

**Comment by Romakita** [comment] 2021-12-08 08:15
@yaritaft  Done. The problem is around the usage of bootstrap

this syntax is wrong:
```typescript
beforeEach(async () => {
   await PlatformTest.boostrap(Server)
})
```
Correct:
```typescript
beforeEach(async () => {
   await PlatformTest.boostrap(Server)()
})
```
or 
```typescript
beforeEach(PlatformTest.boostrap(Server))
```

I pushed a PR on your repository to fix some issue about ts configuration. 

See you
Romain

**Closed as completed by Romakita** 2021-12-08 08:15 UTC
Labels: :bug: bug

**Comment by yaritaft** [comment] 2021-12-11 22:58
@Romakita thank you very much ! Sorry for the delay in my answer, I had a super busy week.
I confirm that your suggestions work perfectly ! I was able to fix my project and improve the testing by using supertest. Thank you very much for that!

Moreover, I really appreciate that you took a look at the rest of the repo and you applied some extra suggestions too. I was stuck with this a lot of time and thank to you I could finish my project :).

Do you want me to send a PR to add a little warning about this in the documentation ? If I can help you somehow please let me know!

Best regards,

Yari

**Comment by Romakita** [comment] 2021-12-12 06:48
Yes you can make a PR ;)
