### ISSUE TITLE
Route add order mechanism

### ISSUE THREAD

**Issue by alexproca** [TypedProject/ts-express-decorators#29] opened 2017-01-13 22:15 UTC
The order of adding routers to express matters. For example if we have following class.

```typescript
@Controller("/account")
export class Account {

  @Get("/:id")
  getAccountById( @PathParam("id") id: string ) {...}

  @Get("/manager")
  getManagerAccount() {...}
}
```
**Request**
`GET /account/manager`

**Expected**
Method `getManagerAccount()` respond

**Actual**
Method `getAccountById()` will respond with `manager` injected as `id`

**Workaround**

```typescript
@Controller("/account")
export class Account {

  @Get("/manager")
  getManagerAccount() {...}

  @Get("/:id")
  getAccountById( @PathParam("id") id: string ) {...}

}
```

**Conclusion**

When adding Routers to express app, fixed routes should go first then parametrised ones.

**Comment by Romakita** [comment] 2017-01-14 08:54
Hello Alex,

You have the same problem when you use the express method.

```typescript
app.get('/account/:id', cb);
app.get('/account/manager', cb);
```

The request `/account/manager` satisfy always the first condition according to the routing list.

It is the responsibility of the developer to put his route in the right order :)

For me isn't a bug.

**Comment by alexproca** [comment] 2017-01-14 08:58
Yes is the same problem (order matters) but I was thinking if we can see routes not starting with `:` and add them first and add `:` starting routes at the end when processing decorators. In this way we can take some burden off the developers shoulder. 

Maybe is not a bug but an improvement.

**Comment by Romakita** [comment] 2017-01-14 09:01
Ok I see. I think, it's a big works and behavior is unpredictable compared to the implementation that the developer will do.

**Comment by alexproca** [comment] 2017-01-14 09:33
But right now is the order of apparition of methods in the class guaranteed to be kept by typescript when constructing method metadata array ?

**Comment by Romakita** [comment] 2017-01-14 14:05
Typescript keeps the declaration order of the methods and therefore associated metadata.

**Comment by zoubarevm** [comment] 2017-01-21 00:46
Hey guys,

It seems like in my case, both routes will get called no matter which order I put them in. The second one would even throw an exception indicating the the headers can no longer be modified (see https://github.com/Romakita/ts-express-decorators/issues/29). 

Is there a way to `handle` a route and prevent it from another controller method from being hit? Maybe it has something to do with the fact I'm returning promises?

Thanks in advance for any help!

**Comment by Romakita** [comment] 2017-01-21 16:02
Hey @zoubarevm . 
Have you a complete example of your controller ? 

- For the header, I see what you mean. Because you have two rules that respond to the request, the   `response.setHeader("X-Managed-By", "Express-router-decorator");` is called once too. I'll fix that.

 - Is there a way to handle a route and prevent it from another controller method from being hit? Maybe it has something to do with the fact I'm returning promises? 

Promises  isn't the cause. TsExpressNext use the nextFunction to call the next middleware. The nextFunction is binded with the promise returned by your method.

Prevent isn't possible because with Express you can add a lot of middleware for one request/route. But I can also be mistaken.

**Comment by Romakita** [comment] 2017-01-21 16:14
Error with `response.setHeader("X-Managed-By", "Express-router-decorator");` is patched with v1.3.1 @zoubarevm ;)

**Comment by zoubarevm** [comment] 2017-01-22 14:41
@Romakita awesome, it seems like it worked.

I also targeted the routes more specifically (by adding a regex to the parameter `(\\d+)`). Seemed like it solved the duplicate route resolution problem.

Thanks for your help!

**Comment by m0uneer** [comment] 2017-03-30 18:57
Hello guys,

I have a weird behavior with routes but first I need to understand something. In my case only order does not solve the problem because I should also inject the `@Next` and the `return` **anything** at the end of the function. So, is this fine?
The weird behavior is that despite being successfully handled the order with the `@Next` and `return`, changing the api logic to work with Async/Await causing the conflict again!

**Code:**
```javascript
  @Authenticated()
  @UseBefore(Middleware)
  @Get(`parent/childs`)
  public async getChilds (
    @Request() req: DjatyRequest,
    @Response() res: Express.Response,
    @Next() next: Express.NextFunction,
  ): Promise <void> {
    console.log('getChilds'); // called
    try {
      const childs = await this.childService.getChilds();
      res.json(childs);
    } catch (err) {
      res.status(400).json({msg: 'error'});
    }
  }

  @Authenticated()
  @Get(`parent/:parentId`)
  public async getParent (
    @PathParams('parentId') parentId: number,
    @Response() res: Express.Response,
    @Next() next: Express.NextFunction,
  ): Promise<void> {
    console.log('getParent'); // is called also!
    try {
      parent = await this.parentService.getParent(parentId);
      res.json(parent);
    } catch (err) {
      res.status(400).json({msg: 'error''});
    }
  }
```

**Comment by m0uneer** [comment] 2017-04-09 13:18
Hello everybody,
I face a similar problem when I return a promise even if route order is fine.
```
  @Get('/new')
  public new (
    @Request() req: Express.Request,
    @Response() res: Express.Response,
  ) {
    console.log('new');
    return new Promise((resolve, reject) => {
      resolve('new');
    }).then(d => {
      res.send(d);
    });
  }

  @Get('/:id')
  public param (
    @PathParams('id') id: string,
    @Request() req: Express.Request,
    @Response() res: Express.Response,
  ) {
    console.log(param);
    res.send(id);
  }
```

**Comment by Romakita** [comment] 2017-04-09 14:23
Hi @m0uneer 
Your problem is that you to use two way to send you response and two methods to intercept an incoming request.

First case:

```typescript
@Get('/new')
  public new (
    @Request() req: Express.Request
  ) {
    console.log('new');
    return new Promise((resolve, reject) => {
      resolve('new');
    });
  }
```
You don't need to use response if you want just return the "new" data. ts-express-decorators will sent the response automatically.

But in some case you need to send manually your response. In this case, don't return a promise.

Just do that:
```typescript
@Get('/new')
  public new (
    @Request() req: Express.Request,
    @Response() res: Express.Response,
  ) {
    console.log('new');
    // remove return instruction.
    new Promise((resolve, reject) => {
      resolve('new');
    }).then(d => {
      res.send(d);
    });
  }
```

In your case you have problem your routes implementation. When you give theses routes:

- /new
- /:id

express will resolve the two routes when the called route is `/new`. But you send response in the first and second routes. You have a conflict => `Error: Can't set headers after they are sent.`. It's pure problem with Express and not with TsExpressDecorators ;).

I will not change the behavior of Express !

So I recommend you to change your implementation to do not have two routes that can be resolved at the same time for one request, if that's not what you want. 

Here an example that will work fine:

```typescript
  @Get('/')  // remove new or change the second routes
  public new (
    @Request() req: Express.Request,
    @Response() res: Express.Response
  ) {
    console.log('new');
    // 1st usecase
   response.send('new');

    // or by promise
    return new Promise((resolve, reject) => {
       resolve('new');
    });
  }

  @Get('/:id')  // or @Get('find/:id') or other stuff that not match with the first route.
  public param (
    @PathParams('id') id: string,
    @Request() req: Express.Request,
    @Response() res: Express.Response,
  ) {
    console.log('param');
    res.send(id);
  }
```

I hope my explanation will help you.

See you,
Romain

**Comment by m0uneer** [comment] 2017-04-10 12:16
@Romakita, Thanks a lot Romain your explanations helps a lot.
Just a question about `invokeMethod()` inside `MiddlewareService` class at `/src/services/middleware.ts` file, 
```
    public invokeMethod(settings: IInjectableMiddlewareMethod, localScope: IInvokableScope): any {
        ...

        return new Promise((resolve, reject) => {
            ...
            Promise
                .resolve()
                .then(() => {
                  ...
                })
                .then((data) => {
                    if (data !== undefined) {
                        localScope.request.storeData(data);
                    }

                    if (!hasNextFn || isPromise) {
                        resolve();
                    }
                })
                .catch(reject);

        })
            .then(
                () => {
                    next();  // <--- Here is my question
                },
                (err) => {
                    next(err);
                }
            );
    }
```

Isn't this `next()` call the responsible for the conflict? What if we just return the response here and let  `next` to be called explicitly if required? I appreciate your explanation very much.

**Comment by m0uneer** [comment] 2017-04-13 09:57
Waiting your prompt response @Romakita

**Comment by Romakita** [comment] 2017-04-14 06:46
Hi @m0uneer,

To use promise with Express, I'm obliged to ask Express to pass me the next function. If I don't get the next function, the middleware will be finished before the Promise has finished his execution.

When you get the next express function, you must to call this. If you don't that, Express wouldn't call the next middleware. Even if you send a response in your middleware, you must call the next express function. But if you use Express, you certainly know this use case to send a response:
```typescript
app.get("/", function (request, response) {
     response.send("data");
});
```
This code don't call the next express function. Express, call implicitly the next function for you ! It's an equivalent to:
```typescript
app.get("/", function (request, response, next) {
     response.send("data");
     next();
});
```
Finally, I take your code in pure express implementation
```typescript
app
 .get("/new", function (request, response) {
        response.send("data1");
  })
  .get("/:id", function (request, response) {
       response.send("data2");
  });
```
You will have a conflict and you will get an error when you call /new => headers are already sent.

---

To answer to your question, here the complete code:
```typescript
 return new Promise((resolve, reject) => {

            let parameters, isPromise: boolean;

            localScope.next = reject;  // ! IMPORTANT

            Promise
                .resolve()
                .then(() => {
                     const result = handler()(...parameters);

                     isPromise = result && result.then;

                     return result;
                })
                .then((data) => {

                    if (data !== undefined) {
                        localScope.request.storeData(data);
                    }

                    if (!hasNextFn || isPromise) {
                        resolve(); // (1)
                    }
                })
                .catch(reject);

        })
            .then(
                () => {
                    next(); //  and (1)
                },
                (err) => {
                    next(err); // (2)
                }
            );

```

The function call that you pointed will be called in this cases:

- Your method return Promise, so the script waiting the resolution of the promise. Final call is (1).

```typescript
myMethod() {
   return Promise.resolve({});
}
```
=> isPromise  = true, hasNextFn = false

- Your method invoke @Next() decorator, so in this case, I inject the reject() function in @Next() decorator. Final call is (2).

```typescript
myMethod(@Next() next) {
    next() // or next(new Error());
}
```
=> isPromise  = false, hasNextFn = true

- Your method return an Object directly. Final call is (1).
```typescript
myMethod() {
   return {};
}
```
=> isPromise  = false, hasNextFn = false

- Your method use classic call:
```typescript
myMethod(request, response, next)
```
=> isPromise  = false, hasNextFn = true

- Your method use next and Promise at the same time:
```typescript
myMethod(@Next()){
    next("next data");
    return Promise.resolve("promise data");
}
```
=> isPromise  = true, hasNextFn = true
In this case, next will be called before the promise. I'm lucky because, the promise can be resolved once a time. So the final call is (2). If I resolve myMethod's promise before next(), it's works too, but the final call is (1). My recommendation is : not to use at the same time Promise and @Next().

But I know, I have one case where this script doesn't works fine:

- Your method doesn't invoke next and doesn't return a Promise:
```typescript
myMethod(request, response){}
```
=> isPromise  = false, hasNextFn = false

See you :)
Romain

**Comment by m0uneer** [comment] 2017-06-19 12:27
> When you get the next express function, you must to call this. If you don't that, Express wouldn't call the next middleware.
I tried a pure javascript installation of express to make sure this behavior is normal but unfortunately, the next middleware is never called without injecting next and calling it.
```javascript
router.get('/test', function (req, res) {
  console.log(1); // logged and server hangs
}, function (req, res, next) {
  console.log(2); // never been called
  res.json();
});
```
And I returned to documentation but couldn't find any useful info about this bahaviour. Could you please refer to the documentation of Express for this?

**Comment by Romakita** [comment] 2017-06-19 12:50
Hi @m0uneer ,

In this case, I'm not sure if express follow the rules that I had explained.  I'll tried ASAP ;)

This example works:
```typescript
router.use(function (req, res) {
  console.log(1); // logged and server hangs
})
.use(function (req, res, next) {
  console.log(2); // logged and server hangs
  next();
})
```
But It didn't work in this case:
```typescript
router.use(function (req, res, next) { // next is injected but never called
  console.log(1); // logged and server hangs
})
.use(function (req, res, next) {
  console.log(2); // never log
  next();
})
```

Here a link on the middleware, maybe you can find the right explication:
http://expressjs.com/en/guide/writing-middleware.html

See you
Romain

**Comment by m0uneer** [comment] 2017-06-22 14:27
I'm sorry, Romain, but you're the first and second example are not working... both only log `1` then server hangs and never log `2` (Tested with a fresh Express installation). The only way to call the next middleware is to inject `next();` and call it (The Express way). But the scenarios you're talking about are not mentioned in the docs and unfortunately will not work.

Personally I like your implementation to call the next middleware only incase `@next()` is injected but I just highlight that this is not the default behaviour of express.

Back to my question, you recommended:
> But in some case you need to send manually your response. In this case, don't return a promise.

Fine but what if I want to use `async/await` or return a promise and in the same time assert and return a custom response inside the controller method? This will require to inject the `@response()` and (implecitely) will be compiled to return a promise. For example
```javascript
  public async getPost (@PathParams('postId') postId: number,
                                     @Response() res: Express.Response) {
    const hasAccess = await this.hasUserAccess(postId);
    if (!hasAccess) {
      res.status(401).json({
        level: 'core',
        redirectUrl: 'A URL'
      });
    }

    return this.postService.getPost(postId);
  }

```
 As I undersand your point of view, this will work properly. So what do you think?

**Comment by Romakita** [comment] 2017-06-22 15:32
Hi @m0uneer,

I'm sorry for the bad example... I'm surprised too.

I have two proposal for your problem :

## With Middleware

```typescript
import {Unauthozised} from "ts-httpexceptions";

@Middleware()
export class AccessPostMiddleware {
   use(@PathParams('postId') postId: number, @Response() response, @Next() next) {
        if(!this.hasUserAccess(postId)) {
          next(new Unauthozised(json.stringify({
             level: 'core',
             redirectUrl: 'A URL'
          })));
        } else {
           next();
        }
   }
   
   private hasUserAccess(postId) {
      return true;
   }
}

@Controller("/")
class SomeClass {

   @Get("/:id")
   @UseBefore(AccessPostMiddleware)
   public async getPost (@PathParams("postId") postId: number) {
       return this.postService.getPost(postId);
   }
}
```
In addition, you can create your custom decorator like this:
```typescript
export function AccessPost (target, propertyKey, descriptor) {
    return UseBefore(AccessMiddleware)(target, propertyKey, descriptor);
}
```
then:
```typescript
@Controller("/")
class SomeClass {

   @Get("/:id")
   @AccessPost
   public async getPost (@PathParams("postId") postId: number) {
       return this.postService.getPost(postId);
   }
}
```

## With throwing exception

```typescript
import {Unauthozised} from "ts-httpexceptions";
class PostCtrl {
  @Get('/posts')
  public async getPost (@PathParams('postId') postId: number) {

    const hasAccess = await this.hasUserAccess(postId);

    if (!hasAccess) {
      throws new Unauthozised(json.stringify({
        level: 'core',
        redirectUrl: 'A URL'
      }));
      
      return;
    }

    return this.postService.getPost(postId);
  }

  @Get('/:id')
  public async anyDummyMethod (){
  }
}
```

Middleware approach is more reusable (with decorator). But it's maybe overkill in your case ^^.

Actually, I work on your problem to solve it in the future version. But, promisify express middleware it's very hard with all possible use case...

See you,
Romain

**Comment by m0uneer** [comment] 2017-06-24 18:15
Thanks Romain for your proposals, but they both don't solve the problem of the conflict. Also the way you throw the `Exception` will return a stringified error message and not a `json`.
Waiting for your prompt response :)

**Comment by m0uneer** [comment] 2017-07-20 16:10
Hi Romain,

Any news about this issue? and  I think it should be `open` not to be forgotten.

Thanks for your help

**Comment by Romakita** [comment] 2017-07-20 21:00
Hi @m0uneer ,

My apologize :(

Have you test the 1.4.11 ? I've added some fix about this feature. If this version didn't solve it, you can set the `debug` option to `true` on the serverSettings.

```typescript
@ServerSettings({debug: true})
class Server extends ServerLoader {}
```
Send me the log trace when you have your error :) (since the first trace with incoming request).

See you,
Romain

**Comment by m0uneer** [comment] 2017-07-25 11:22
Thanks, Romain,

I tried your last version but routes still conflict.

This is an example (of many) to reproduce the conflict

```javascript
  @Get('/test')
  public test () {
    return 'test';
  }

  @Get('/:id')
  public get (@PathParams('id') id: number) {
    return 'id';
  }
```
**Log Trace:**
```javascript
[DEBUG] [#1] -- Incoming request --------------------------------------------------------
[DEBUG] [#1] Route => GET /api/test
[DEBUG] [#1] Request.id => 1
[DEBUG] [#1] Headers => {"host":"192.168.1.101:3020","connection":"keep-alive","postman-token":"1f5979d6-aec3-0bc4-11fb-aa1c555424c4","cache-control":"no-cache","x-postman-interceptor-id":"79cdef0f-5d41-1789-6dc7-d240ff1ec67f","xsrf-token":"P4OFDp6A-a12J4GvdL-t3TCO7YcFecqBa07w","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36","content-type":"application/json","accept":"*/*","accept-encoding":"gzip, deflate, sdch, br","accept-language":"en-US,en;q=0.8,ar;q=0.6,ru;q=0.4,nl;q=0.2","cookie":"connect.sid=s%3AQtiXZlJ6-nFj6Rg5Hqw0YTOH62HnzG5J.tQj9yaWp6vRLetRjnpT7X6UtDJU2htbsEc1FXAMroWs"}
[DEBUG] [#1] ----------------------------------------------------------------------------
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":false}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"cookieParser","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"cookieParser","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"compression","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"compression","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"jsonParser","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"jsonParser","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"urlencodedParser","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"urlencodedParser","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"session","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"session","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"bound initialize","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"bound initialize","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"bound authenticate","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"bound authenticate","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[WARN ] [#1] [INVOKE][DUPLICATE] The handler have been resolved twice. See your code and find if you use @Next() and Promise at the same time.
[WARN ] [#1] [INVOKE][DUPLICATE] Trace: {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true,"returnPromise":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true,"returnPromise":true}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true,"returnPromise":true}
[DEBUG] [#1] Endpoint => {"target":"Ctrl","methodClass":"test","httpMethod":"get"}
[DEBUG] [#1] [INVOKE][START] {"type":"ENDPOINT","target":"Ctrl","methodName":"test","injectable":false,"hasNextFn":false}
[DEBUG] [#1] [INVOKE][END  ] {"type":"ENDPOINT","target":"Ctrl","methodName":"test","injectable":false,"hasNextFn":false,"data":"test"}
[DEBUG] [#1] [INVOKE][START] {"type":"MIDDLEWARE","target":"SendResponseMiddleware","methodName":"use","injectable":true,"hasNextFn":false}
[WARN ] [#1] [INVOKE][DUPLICATE] The handler have been resolved twice. See your code and find if you use @Next() and Promise at the same time.
[WARN ] [#1] [INVOKE][DUPLICATE] Trace: {"type":"MIDDLEWARE","target":"anonymous","injectable":false,"hasNextFn":true,"returnPromise":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"MIDDLEWARE","target":"SendResponseMiddleware","methodName":"use","injectable":true,"hasNextFn":false}
[DEBUG] [#1] Endpoint => {"target":"Ctrl","methodClass":"get","httpMethod":"get"}
[DEBUG] [#1] [INVOKE][START] {"type":"ENDPOINT","target":"Ctrl","methodName":"get","injectable":true,"hasNextFn":false}
[WARN ] [#1] [INVOKE] {"name":"BAD_REQUEST","type":"HTTP_EXCEPTION","status":400,"message":"Bad request, parameter request.params.id. Cast error. Expression value is not a number."}

[DEBUG] [#1] [INVOKE][START] {"type":"ERROR","target":"bound $onError","injectable":false,"hasNextFn":true}
BadRequest {
  name: 'BAD_REQUEST',
  type: 'HTTP_EXCEPTION',
  status: 400,
  message: 'Bad request, parameter request.params.id. Cast error. Expression value is not a number.' }
[DEBUG] [#1] [INVOKE][START] {"type":"ERROR","target":"GlobalErrorHandlerMiddleware","methodName":"use","injectable":true,"hasNextFn":true}
[DEBUG] [#1] [INVOKE][END  ] {"type":"ERROR","target":"GlobalErrorHandlerMiddleware","methodName":"use","injectable":true,"hasNextFn":true,"error":{}}
[WARN ] [#1] [INVOKE] Error: Can't set headers after they are sent. 
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (server/node_modules/express/lib/response.js:730:10)
    at ServerResponse.res.json (server/dist/app.js:131:28)
    at Server.$onError (server/dist/app.js:216:13)
    at server/node_modules/ts-express-decorators/src/services/middleware.ts:283:45
    at propagateAslWrapper (server/node_modules/async-listener/index.js:468:23)
    at server/node_modules/async-listener/glue.js:188:31
    at server/node_modules/async-listener/index.js:505:70
    at server/node_modules/async-listener/glue.js:188:31
[WARN ] [#1] [INVOKE] Error: Can't set headers after they are sent. 
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (server/node_modules/express/lib/response.js:730:10)
    at ServerResponse.res.json (server/dist/app.js:131:28)
    at Server.$onError (server/dist/app.js:216:13)
    at server/node_modules/ts-express-decorators/src/services/middleware.ts:283:45
    at propagateAslWrapper (server/node_modules/async-listener/index.js:468:23)
    at server/node_modules/async-listener/glue.js:188:31
    at server/node_modules/async-listener/index.js:505:70
    at server/node_modules/async-listener/glue.js:188:31
info: GET /api/test 400 959ms statusCode=400, url=/api/test, host=192.168.1.101:3020, connection=keep-alive, postman-token=1f5979d6-aec3-0bc4-11fb-aa1c555424c4, cache-control=no-cache, x-postman-interceptor-id=79cdef0f-5d41-1789-6dc7-d240ff1ec67f, xsrf-token=P4OFDp6A-a12J4GvdL-t3TCO7YcFecqBa07w, user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36, content-type=application/json, accept=*/*, accept-encoding=gzip, deflate, sdch, br, accept-language=en-US,en;q=0.8,ar;q=0.6,ru;q=0.4,nl;q=0.2, cookie=connect.sid=s%3AQtiXZlJ6-nFj6Rg5Hqw0YTOH62HnzG5J.tQj9yaWp6vRLetRjnpT7X6UtDJU2htbsEc1FXAMroWs, method=GET, httpVersion=1.1, originalUrl=/api/test, , responseTime=959
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (server/node_modules/express/lib/response.js:730:10)
    at ServerResponse.res.json (server/dist/app.js:131:28)
    at Server.$onError (server/dist/app.js:216:13)
    at server/node_modules/ts-express-decorators/src/services/middleware.ts:283:45
    at propagateAslWrapper (server/node_modules/async-listener/index.js:468:23)
    at server/node_modules/async-listener/glue.js:188:31
    at server/node_modules/async-listener/index.js:505:70
    at server/node_modules/async-listener/glue.js:188:31

```

The Express way, a request to  `/test` should response with 'test' and should never - by any mean - reach `/:id`. We, thankfully, agreed on this on the previous replies. And also agreed that the **only way** to let the request reach `/:id` is to call `next()` **explicitly**, this is Express. 

You're implementations consider some useful use cases but they are strange for someone familiar with Express known use cases. Also, those implementations are causing problems and there are no **working** proposals from your replies above.

Thanks for your sincere patience and support, Romain

Mouneer

**Comment by Romakita** [comment] 2017-07-25 11:29
Hi @m0uneer ,

I'll fix that ASAP. Thanks for the log trace :)
Romain

**Comment by m0uneer** [comment] 2017-07-25 14:26
Thanks, Romain :)

**Comment by Romakita** [comment] 2017-07-26 05:32
HI @m0uneer ,

It's fixed :D  v1.4.12

See you

**Comment by m0uneer** [comment] 2017-07-26 10:12
Thanks, Romain,

The conflict itself has been fixed but what if I want to navigate through two route handlers

```javascript
  @Get('/:id')
  public assert (@PathParams('id') id: number,
                         @Next() next: Function) {
    return assert().then(() => { // Please notice that `return` here is not optional if i want use async/await. e,i `public async assert()`.
      next(); // I expect `next()` to call the next handler but it doesn't.
    });
  }

  @Get('/:id')
  public get (@PathParams('id') id: number) {
    // This handler isn't called.
    return 'id';
  }
```

Thanks a lot Romain

**Comment by Romakita** [comment] 2017-07-26 11:26
I thinks if you try the same example in express version, you'll have the same problem :)
(I'm sure because I'd just tested this case). 
Here the pure express implementation:
```typecript
app.get(':id', (request, response, next) => {
   console.log('ID1');
   Promise.resolve().then(() => {
      next();
    });
})

app.get(':id', (request, response) => { // will be ignored by express
   console.log('ID1');
   response.send("id")
})
```

I thinks your approach isn't the good way. Two handler on the same route add twice with app.get() (or other method) will give a problem.

If you need to have to handler on same route, you need to use the first handler as middleware and the second as an Endpoint.

So you can solve your problem like this:
```typescript
  public assert (@PathParams('id') id: number,
                         @Next() next: Function) {
    return Promise.resolve().then(() => {
      next(); // not necessary normally but why not, I accept this challenge :p
    });
  }

  @Get('/:id', this.assert)
  public get (@PathParams('id') id: number) {
    // This handler isn't called.
    return 'id';
  }
```
> This solution is described on https://github.com/Romakita/ts-express-decorators/wiki/Controllers

But with the experience, I'll preferred to use Middleware abstraction with the decorators.

Maybe you case try this:
```typescript
@Middleware()
export class CustomMiddleware {
   use(@PathParams('id') id: number,
                         @Next() next: Function) {
      return Promise.resolve().then(() => {
         next(); // not necessary normally but why not, I accept this challenge :p
      });
   }
}

@Controller("/")
class SomeClass {

  @Get("/:id")
  @UseBefore(CustomMiddleware)
  public get (@PathParams('id') id: number) {
    // This handler isn't called.
    return 'id';
  }
}
```
> You can see the middleware documentation https://github.com/Romakita/ts-express-decorators/wiki/Middlewares

You have the choice :)
See you,
Romain

**Comment by m0uneer** [comment] 2017-07-27 14:41
I will try it myself today and let you know ... thanks again Romain

**Comment by m0uneer** [comment] 2017-08-01 13:58
> I thinks if you try the same example in express version, you'll have the same problem :)
> (I'm sure because I'd just tested this case).
> 
Unfortunately, I tried it and I found it valid express implementation. (I'm also sure :D, I've just tested it)

Also, I see that my approach is good because:
1. I'm filtering the requests. I don't need the request reach the endpoint if it has something wrong.
1. I agree that it can be reached with a decorator or a middleware, but I see (depending on use cases) it just duplications. Why should I add the decorator/middleware for each endpoint? this also increases the potential of a human mistake.
1. more code, dependencies, testing, maintenance, ...

So I see it's a bug :)

Thanks, Romain

**Comment by Romakita** [comment] 2017-08-01 14:06
Well, if your example with Express work can you forward me  the code. Maybe I forgot something.

**Comment by Romakita** [comment] 2017-08-01 14:18
Sorry. I'll just re tested this case with another projet and you've right... never answer to a question when I'm tired XD. I'll inspect the problem and fix that.

**Comment by Romakita** [comment] 2017-08-01 15:08
Fixed with v1.4.15

**Comment by m0uneer** [comment] 2017-08-01 16:16
Great Romain ... Thanks for your support :)

**Comment by Romakita** [comment] 2017-08-01 17:09
@m0uneer And thanks for your patience ^^.

**Comment by ArtemDerevnjuk** [comment] 2019-04-26 16:33
@Romakita seems this bug raised up in v5.9.0 again

**Comment by Romakita** [comment] 2019-04-26 17:15
Hi @ArtemDerevnjuk,

I’ll check that tomorrow, but It should works. It’s covered by one of my e2e test :)

**Comment by Romakita** [comment] 2019-04-27 10:26
Hello @ArtemDerevnjuk 
For me all works as expected.
Here e2e test https://github.com/TypedProject/ts-express-decorators/blob/production/test/integration/response.spec.ts
And his controller with the different response scenario:
https://github.com/TypedProject/ts-express-decorators/blob/production/test/integration/app/controllers/responses/ResponseScenarioCtrl.ts

Can check different example and tell if one of this match with your usecase/issue or not. Probably I missed something, but today all usecases described in ResponseScenarioCtrl are officially supported.

See you,
Romain

**Comment by ArtemDerevnjuk** [comment] 2019-04-27 11:08
@Romakita Hi) Thanks for quick reply!
I'll test again, if I find something I'll write you here.

**Comment by Romakita** [comment] 2019-05-09 11:37
Problem with the different endpoints which have the same or near route pattern. In progress

**Closed** 2019-05-09 14:33 UTC
Labels: bug, enhancement

**Comment by vembry** [comment] 2021-02-09 18:02
sorry for commenting on an old post, but i just want to make sure, that there are no code fix/improvement for this _un-orderly_ path declaration?

e.g if i have something like below
```
  @Get("/:documentId")
  @(Returns(200, Document).Description("get single document"))
  getByDocumentId(
    @HeaderParams("x-token") token: string, 
    @PathParams("documentId") documentId: number
  ): Document {
    return this.documentService.getDocumentById(documentId);
  }

  @Get("/q")
  @(Returns(200, Array).Of(Document).Description("search documents"))
  getBySearch(
    @HeaderParams("x-token") token: string, 
    @QueryParams("content") searchText: string
  ): Document[] {
    return this.documentService.getDocuments();
  }
```

i'd have to switch and declare `/q`  before `/:documentId` like below?
```
  @Get("/q")
  @(Returns(200, Array).Of(Document).Description("search documents"))
  getBySearch(
    @HeaderParams("x-token") token: string, 
    @QueryParams("content") searchText: string
  ): Document[] {
    return this.documentService.getDocuments();
  }
  
  @Get("/:documentId")
  @(Returns(200, Document).Description("get single document"))
  getByDocumentId(
    @HeaderParams("x-token") token: string, 
    @PathParams("documentId") documentId: number
  ): Document {
    return this.documentService.getDocumentById(documentId);
  }
  ```
  
 to prevent  request went to `/:documentId` instead of `/q`, is it like that?

**Comment by Romakita** [comment] 2021-02-09 22:53
@vembry yes you have to switch methode order (like with a pure express app).

**Comment by vembry** [comment] 2021-02-13 03:39
i apologize, apparently it's already covered in the documentation [here](https://tsed.io/docs/controllers.html#routes-order)

**Comment by Romakita** [comment] 2021-02-13 09:01
No worries ;)
