### ISSUE TITLE
How to get provider instances in runtime?

### ISSUE THREAD

**Issue by ringolin93** [TypedProject/ts-express-decorators#647] opened 2019-09-18 09:08 UTC
## Information

- **Version:** 5.27.4
- **Type:** Question

## Description
I have some static methods that may use other providers which have to be retrieved in runtime.
If I use DI in class constructor, I have to change all the static methods to instance method.

Are there any static utility functions can retrieve component in runtime like ```ProviderContext.getProvider<T>(provide: TokenProvider) : T```?

Also is there any method to check whether the application finish initialization or not? this can prevent retrieving any uninitialized component. Thank you :)

**Comment by Romakita** [comment] 2019-09-18 09:30
Hello,
Isn't possible. Injector is built when the server is loaded. The context is the Server instance. So by design isn't possible.

If you want to call static method in instance method, you have to give your service by parameters


> Also is there any method to check whether the application finish initialization or not? this can prevent retrieving any uninitialized component
```typescript
class MyService{
  $onReady() {
     // server is ready
  }
}

```
more info here: http://tsed.io/docs/hooks.html

**Comment by ringolin93** [comment] 2019-09-19 02:26
Thanks for fasy reply. Finally I resolve it by using singleton server:
```
class MyServer extends ServerLoader {
    public static getInstance(): MyServer {
        //Singleton
    }
}
```

And then retrieve the provider from the singleton In the static method:
```
let provider: MyProvider | undefined = MyServer.getInstance()
                    .injector
                    .get<MyProvider>(MyProvider);
```

**Comment by ringolin93** [comment] 2019-09-19 02:26
Thanks for reply. Finally I resolve it by using singleton server:
```
class MyServer extends ServerLoader {
    public static getInstance(): MyServer {
        //Singleton
    }
}
```

And then retrieve the provider from the singleton In the static method:
```
let provider: MyProvider | undefined = MyServer.getInstance()
                    .injector
                    .get<MyProvider>(MyProvider);
```

**Comment by Romakita** [comment] 2019-09-19 06:10
Yes, This is the only way to get injector outside the server context :)
See you

Note: Don't forget to close this issue ;)

**Closed** 2019-09-19 07:39 UTC
