### ISSUE TITLE
[BUG] serializer does not work array of object

### ISSUE THREAD

**Issue by ktalebian** [TypedProject/ts-express-decorators#2533] opened 2023-11-17 00:47 UTC
### Describe the bug

Since 7.36.0 version, if you have a custom type and it is used as an array within another object, it does not work, unless you annotate it with `@CollectionOf`

Here is an example of a controller:

```ts
@Controller("/")
export class HelloWorldController {
  @Get("/single")
  get() {
    const user = new User();
    user.id = new Id();
    user.name = 'test';
    
    return user;
  }

  @Get("/object")
  object() {
    const user1 = new User();
    user1.id = new Id();
    user1.name = 'user1';

    const user2 = new User();
    user2.id = new Id();
    user2.name = 'user2';
    
    return {
      user1,user2
    };
  }

  @Get("/list")
  list() {
    const user1 = new User();
    user1.id = new Id();
    user1.name = 'user1';

    const user2 = new User();
    user2.id = new Id();
    user2.name = 'user2';

    const list = new List();
    list.users.push(user1);
    list.users.push(user2);
    
    return list;
  }

  @Get("/collection")
  collection() {
    
    const user1 = new User();
    user1.id = new Id();
    user1.name = 'user1';

    const user2 = new User();
    user2.id = new Id();
    user2.name = 'user2';

    const collection = new Collection();
    collection.users.push(user1);
    collection.users.push(user2);
    
    return collection;
  }
}
```

with the objects being

```ts
function IdProperty() {
  return useDecorators(
    Property(String),
    OnDeserialize((id) => {
      console.log('OnDeserialize', id)
      if (id) {
          return new Id(id);
      }
    }),
    OnSerialize((id) => {
      console.log('onSerialize', id)
      if (id) {
        return id.getValue();
      }

      return null;
    }),
  );
}

export class Id {
    protected value: string;

    public constructor(id?: string) {
        if (id) {
            this.value = id;
        } else {
            this.value = uuid();
        }
    } 

    public getValue(): string {
        return this.value;
    }
  }

export class User {
    @IdProperty()
    id: Id;

    @Property()
    name: string;
}

class List {
  users: User[];

  constructor() {
    this.users = [];
  }
}

class Collection {
  @CollectionOf(User)
  users: User[];

  constructor() {
    this.users = [];
  }
}
```

The output of these 4 endpoints are:

```bash
❯ curl localhost:8083/single | jq .
{
  "id": "b6b05b6b-6cde-4b85-b00c-b1a4769ad774",
  "name": "test"
}

❯ curl localhost:8083/object | jq .
{
  "user1": {
    "id": "3312f798-d044-41e1-9c4a-b6e18e4d3cba",
    "name": "user1"
  },
  "user2": {
    "id": "7b1e6d5c-3548-4add-8d15-3bb1f40944b3",
    "name": "user2"
  }
}

❯ curl localhost:8083/list | jq .
{
  "users": [
    {
      "id": {
        "value": "3e6f86b8-5cde-47a8-9042-e2c102162994"
      },
      "name": "user1"
    },
    {
      "id": {
        "value": "fa70d1cc-348e-447c-a883-6a7207067166"
      },
      "name": "user2"
    }
  ]
}

❯ curl localhost:8083/collection | jq .
{
  "users": [
    {
      "id": "7aff92cf-4ea5-453c-89f4-c2f920f4439c",
      "name": "user1"
    },
    {
      "id": "d74704bc-85ad-4547-815e-07b0239cefa8",
      "name": "user2"
    }
  ]
}
```

### To Reproduce

Run the repo

### Expected behavior

I don't expect to see

```
"id": {
   "value": "3e6f86b8-5cde-47a8-9042-e2c102162994"
},
```

when it is nested

### Repository URL example

Run https://github.com/ktalebian/tsed-bug application

### OS

macOS

### Node version

Node 18

### Library version

7.44.0

**Comment by Romakita** [comment] 2023-11-18 09:26
Hello @ktalebian 
As I see, there is some mistake in your example, it explain why you haven't the expected result. The new json-mapper is more strict and needs a correct usage of the decorators. Before, the json-mapper was lax and allowed certain bad practices to pass, but it had a huge cost on performance. I had to make a choice so that the json-mapper would be faster, and meet the expectations of devs using the Ts.ED framework.

Moreover, you would have noticed these errors if you had the generation of the swagger doc to install in your example ;)

For example:

Wrong but works because json-mapper infer the user directly from result.
```ts
  @Get("/single")
  @Returns(200)
  get() {
    const user = new User();
    user.id = new Id();
    user.name = "test";

    return user;
  }
```
> <img width="587" alt="Capture d’écran 2023-11-18 à 10 06 33" src="https://github.com/tsedio/tsed/assets/1763311/90467d2f-ec50-462c-b287-e2e39416c642">

Recommanded:
```ts
  @Get("/single")
  @Returns(200, User)
  get() {
    const user = new User();
    user.id = new Id();
    user.name = "test";

    return user;
  }
```
>  <img width="587" alt="Capture d’écran 2023-11-18 à 10 06 08" src="https://github.com/tsedio/tsed/assets/1763311/ad00ff22-cd1f-4920-921e-5683e4460851">

For collection example, I really haven't understood why you create an model to store list where Ts.ED provide in his documentation an example to return a list of models!!! But maybe it's just a model that wrap many property so the behavior is the same as I explained in the first section. But using `Returns` decorator is always better ;)

```ts
  @Get("/collection")
  @Returns(200, Collection)
  collection() {
    const user1 = new User();
    user1.id = new Id();
    user1.name = "user1";

    const user2 = new User();
    user2.id = new Id();
    user2.name = "user2";

    const collection = new Collection();
    collection.users.push(user1);
    collection.users.push(user2);

    return collection;
  }
```
But can be simplified by this:

```ts
  @Get("/collection")
  @Returns(200, Array).Of(User)
  collection() {
    const user1 = new User();
    user1.id = new Id();
    user1.name = "user1";

    const user2 = new User();
    user2.id = new Id();
    user2.name = "user2";

    return [user1, user2];
  }
```
> <img width="587" alt="Capture d’écran 2023-11-18 à 10 12 03" src="https://github.com/tsedio/tsed/assets/1763311/2da8cc17-cf43-4558-a669-e1dd3c8e09c4">

So now, the last point, it's a bit tricky. Object is considered by `json-mapper` as not being a model, so by definition, there is no metadata to transform instance to json. So why try to apply the json-mapper on it as much as save time and return the object directly. 
I don't particularly want to bring back the previous behavior for this specific case because it is one of the points which strongly impacts the performance of the mapper. 

The json-mapper need always at least a collection of User (Map, Set, Array) or a class instance to work by inference. There is no solution to use Object using `@Returns` decorator but a workaround is possible using Map:

```ts
  @Get("/object")
  @Returns(200, Map).Of(User)
  object() {
    const user1 = new User();
    user1.id = new Id();
    user1.name = "user1";

    const user2 = new User();
    user2.id = new Id();
    user2.name = "user2";

    const map = new Map();
    map.set("user1", user1);
    map.set("user2", user2);
    return map;
  }
```

The enhancement could be to improve `Returns` decorator to instrument the json-mapper correctly in this case:

```ts
  @Get("/object")
  @Returns(200, Records).Of(User) // need a special class 
  @Returns(200).RecordsOf(User) // need just a flag to allow {[key]: User}
  object() {
    const user1 = new User();
    user1.id = new Id();
    user1.name = "user1";

    const user2 = new User();
    user2.id = new Id();
    user2.name = "user2";

    return {user1, user2};
  }
```

See you

**Comment by ktalebian** [comment] 2023-11-21 20:44
@Romakita thanks, but the main problem has been with the usage of 

```ts
class List {
  users: User[];

  constructor() {
    this.users = [];
  }
}
```

When using `@Returns(200, List)` is not solving the issue. This is just a dummy example, the more practical use case is something like

```ts
class Page<T> {
  result: T[];
  metadata: PageMetadata;
}
```

Hence why this is a "class" and not `@Returns(200, Records).Of(User) ` because other properties exist. 

Unless I decorate the `result` with `CollectionOf`, I am not getting the proper serialization. And since this is a generic/unknown type, I do not know what to pass. 

In the example above, try to do the curl on `/list` endpoint - it will not come out right, no matter what decorators of `Returns` you use.

**Comment by Romakita** [comment] 2023-11-21 20:49
@ktalebian but if you change the usecase, I can give you the correct working example. I don’t understand your problem. CollectionOf is mandatory if the property is an array. The doc is clear around that. So please clarify your issue and  don't mix everything otherwise we won't get through it.

see you

**Comment by ktalebian** [comment] 2023-11-22 01:41
Alright, I cleaned the sample code. The class I'm trying to return has a property that will be an array. But this array is of unknown type. 

Imagine having `listUsers` and `listHosts` as two separate endpoints. Both would return a response of type `{list: Array<T>, meta: Metaobject}` where `list` in case of `listUsers` is `User[]` and in case of `listHosts` is `Host[]`.

This `User/Host` class has an `Id` and the serialization is not happening with the new json-mapper.

```ts
@Controller("/")
export class HelloWorldController {
  @Get("/single")
  @Returns(200, User)
  get() {
    const user = new User();
    user.id = new Id();
    user.name = 'test';
    
    return user;
  }

  @Get("/users")
  @Returns(200, Page)
  users() {
    const user1 = new User();
    user1.id = new Id();
    user1.name = 'user1';

    const user2 = new User();
    user2.id = new Id();
    user2.name = 'user2';

    const meta = new PageMeta(1, user2.id);
    return new Page([user1, user2], meta);
  }

  @Get("/hosts")
  @Returns(200, Page)
  hosts() {
    const host1 = new Host();
    host1.id = new Id();
    host1.name = 'host1';

    const host2 = new Host();
    host2.id = new Id();
    host2.name = 'host2';

    const meta = new PageMeta(1, host2.id);
    return new Page([host1, host2], meta);
  }
}
```

Where the objects are

```
class PageMeta {
  direction: number;
  token: Id;

  constructor(direction: number, token: Id) {
    this.direction = direction;
    this.token = token;
  }
}

class Page<T> {
  // This is where you normally have CollectionOf, but the type of `T` is generic
  list: T[];
  metadata: PageMeta;

  constructor(items: T[], meta: PageMeta) {
    this.list = items;
    this.metadata = meta;
  }
}
```

Is this more clear?  I do not know how to use `CollectionOf` on the class `Page` since `list` is a generic type - it can be a list of `User` or a list of `Host`

I can create a base `IdCrud` that both `User/Host` extend and then use 

```ts
class Page<T extends IdCrud> {
  @CollectionOf(IdCrud)
  list: T[];
```

And that works just fine, except I want my `Page` to be more generic - some page items would not necessarily have an `id`

**Comment by Romakita** [comment] 2023-11-22 06:38
Hello @ktalebian 
Yes it's more clear. And now, I can said you that "Generics" are covered since a long time by Ts.ED, there is a dedicated section here: https://tsed.io/docs/model.html#generics

I didn't understand why it was a bug. Now, I see you just haven't read the documentation ;) Ts.ED philosophy is to use at least on decorator per property on model (it's . So your given is wrong. 

<img width="891" alt="Capture d’écran 2023-11-22 à 07 24 53" src="https://github.com/tsedio/tsed/assets/1763311/b1c654c1-a9c2-4408-ae85-2796bfc76223">

Here is the correct example:


```ts
@Generics("T")
class Page<T> {
  @CollectionOf("T")
  list: T[];

  @Property() // also mandatory!
  metadata: PageMeta;

  constructor(items: T[], meta: PageMeta) {
    this.list = items;
    this.metadata = meta;
  }
}
```

I let you read the documentation to found the correct usage in your controller ;)

> I strongly encourage you to use the `@tsed/swagger` plugin in your project. In fact, it would have allowed you to detect that decorators were missing on your models.

and to clarify this issue, it's not a bug because:
- The documentation explain how to instrument the Generics models since v6.
- Ts.ED needs at least one decorator on property to serialize/deserialize correctly a model/Json Object. Starting from this principle, any behavior that could work without the use of decorators cannot be taken for granted. Which is the case here :)

I close this issue and my apologize for the time wasted on understanding your problem ;)

See you

**Closed as completed by Romakita** 2023-11-22 06:38 UTC
Labels: :grey_question: question

**Comment by ktalebian** [comment] 2023-11-22 07:22
@Romakita Ts.ED is _magic!_ I need to one day spend some quality time and learn the codebase!

Thank you!
